import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import RootWrapper from '@/components/RootWrapper';
import Header from '@/components/Header';

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable}`}>
        <RootWrapper className="min-h-screen antialiased flex flex-col items-center justify-center">
          <Header />
          {children}
        </RootWrapper>
      </body>
    </html>
  );
}
